### ISSUE TITLE
"Dock" parameter missing?

### ISSUE THREAD

**Issue by RMRNC1** [RobU23/ReaScripts#17]
Hiya Rob,

Any idea how to fix this issue when I try to pull your script through MIDI editor?

"...s\MIDI Editor\MIDI Ex Machina\RobU - MIDI Ex Machina.lua:1178: Function 'dock' requires 1 parameters, 5 passed"

Thanks matey,

R

**Comment by RobU23** [comment]
Hi,

Strange bug !

Can you tell me which version of the scripts that you're running? (highly recommend the latest version)

Did you install it using ReaPack? (highly recommend using ReaPack too.. :) )

Which OS do you use (Windows / Mac / Linux)?

Do you have more than 1 monitor?

Which screen are you starting the script on?

Does this happen at the start of the script?

Has the script ever worked for you, or has it always been broken?


Cheers
Rob

**Comment by RMRNC1** [comment]
Thanks for the quick reply,

It never worked for me unfortunately. I've just installed reapack and downloaded everything through it (so I'm assuming im running the latest and greatest).

I'm on Windows 8, 64 bit. And yes, it does happen as soon as I try to load through the actions tab.

Ta,

R

**Comment by RobU23** [comment]
Yeah, you should have the latest version.

When you say 'pull or lead' thru the actions tab, do you mean you're running it using the default installed action?  (I think this is what you mean)

Do you have more than 1 monitor?  If so, what happens if you move Reaper, or the Midi Editor to another window?

That line number and function you pointed out captures the window position of the script so that when it's resized it doesn't go back to it's default position... That particular function is not described in much detail in the Reaper API unfortunately - that said, I run Win10 64 bit but only on one monitor, and never seen this issue before :|

**Comment by RMRNC1** [comment]
Good news fella,

Just updated my reaper to the latest version and its all looking good now. Strange one! 

Not sure if you wanna follow this up or not, but all looking fine now.

Thanks for your hard work mate, lovely piece of kit this script ;)

All the best,

R

**Comment by RobU23** [comment]
All good, glad it's working 👍
