### ISSUE TITLE
Is there a way to use MIDI Ex Machina as a plugin, not an action?

### ISSUE THREAD

**Issue by RichardJECooke** [RobU23/ReaScripts#21]
Hi, I love your script, thanks. 
But is there a way to use it from FX menu?  I don't want to generate MIDI and be forced to hardcode it as MIDI data, I want to keep it as settings in the plugin so I can automate them dynamically, like every other plugin (like the MIDI randomiser plugin currently works)

**Comment by RobU23** [comment]
Hi Richard - Short answer is no, unfortunately.  Machina is a Lua script, and in Reaper these can only be run from the actions menu (or via a keypress, or toolbar icon shortcut).  

A longer answer is still no :) However it could (in theory) be ported to Jesusonic to run as a real-time MIDI effect (which, I suspect, is what the MIDI randomiser you mentioned is), but it would be a Herculean effort to port not only the randomising/generation code, but also the GUI.  As I know absolutely zero JSFX (EEL2) it's not something I would think about taking on.  Same would apply to a port to a VST format (C/C++).

I am working on v2 (which is why v1 hasn't seen any updates for so long), but it is still be a Lua script and will have the same limitations as every other Lua script.
