### ISSUE TITLE
RobU - MIDI Ex Machina.lua:387: bad argument #1 to 'GetMediaItemInfo_Value' (MediaItem expected)

### ISSUE THREAD

**Issue by Eisenspalter** [RobU23/ReaScripts#23]
Hi,
I tried Ex Machina and got this error:
RobU - MIDI Ex Machina.lua:387: bad argument #1 to 'GetMediaItemInfo_Value' (MediaItem expected)

**Comment by RobU23** [comment]
Hi Mario,

Machina only works in the main Midi Editor.  The usual method for starting it would be to open an existing MIDI item, then run the script (I have it mapped to the 'M' key in the midi editor for convenience).  If you deselect the MIDI item in the arrange window, it **should** show a message in the GUI ('no item selected'), in which case you can select another midi item to work on, but this is not entirely reliable, in which case you might also see this error (I think this is due to a MIDI editor preference, but I'd need to do some testing).

Do you always get this error, or just sometimes?

Rob
